'use client';
import { FormEvent,useEffect,useMemo,useState } from 'react';
import { createBrowserSupabase } from '@/lib/supabase/client';

type Msg={id:string;body:string;sender_role:string;created_at:string};
export default function Support(){
 const [conversation,setConversation]=useState<string|null>(null);const [messages,setMessages]=useState<Msg[]>([]);const [body,setBody]=useState('');const s=useMemo(()=>createBrowserSupabase(),[]);
 async function load(){const {data:{user}}=await s.auth.getUser();if(!user){location.href='/login';return;}let {data:c}=await s.from('support_conversations').select('id').eq('user_id',user.id).in('status',['open','pending']).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!c){const {data:m}=await s.from('membership_accounts').select('id').eq('user_id',user.id).maybeSingle();const {data:newC}=await s.from('support_conversations').insert({user_id:user.id,membership_id:m?.id||null,subject:'会员咨询',status:'open',priority:'normal',last_message_at:new Date().toISOString()}).select('id').single();c=newC;}if(c){setConversation(c.id);const {data:m}=await s.from('support_messages').select('id,body,sender_role,created_at').eq('conversation_id',c.id).order('created_at');setMessages((m||[]) as Msg[]);}}
 useEffect(()=>{load();},[]);
 async function send(e:FormEvent){e.preventDefault();if(!conversation||!body.trim())return;const {data:{user}}=await s.auth.getUser();if(!user)return;const now=new Date().toISOString();await s.from('support_messages').insert({conversation_id:conversation,user_id:user.id,sender_role:'member',sender_user_id:user.id,body,content_type:'text'});await s.from('support_conversations').update({status:'open',last_message_at:now,updated_at:now}).eq('id',conversation);setBody('');load();}
 return <main className="shell"><div className="top"><div className="brand">联系客服</div><a href="/">返回</a></div><div className="card"><div className="list">{messages.map(m=><div className="row" key={m.id}><div><strong>{m.sender_role==='member'?'我':'客服'}</strong><div>{m.body}</div></div><span className="muted">{new Date(m.created_at).toLocaleString()}</span></div>)}</div><form onSubmit={send} style={{display:'flex',gap:10,marginTop:18}}><input className="input" value={body} onChange={e=>setBody(e.target.value)} placeholder="请输入问题" required/><button className="btn">发送</button></form></div></main>}
