'use client';
import { FormEvent,useEffect,useState } from 'react';
import { createBrowserSupabase } from '@/lib/supabase/client';

type Section='members'|'benefits'|'feedback'|'support'|'navigation'|'notifications';
const sections:[Section,string][]=[['members','会员'],['benefits','权益'],['feedback','反馈'],['support','客服'],['navigation','导航'],['notifications','通知']];

export default function Admin(){
  const [section,setSection]=useState<Section>('members');const [rows,setRows]=useState<any[]>([]);const [summary,setSummary]=useState<any>(null);const [token,setToken]=useState('');const [error,setError]=useState('');const [msg,setMsg]=useState('');
  async function auth(){const s=createBrowserSupabase();const {data:{session}}=await s.auth.getSession();if(!session){location.href='/login';return '';}setToken(session.access_token);return session.access_token;}
  async function load(sec:Section=section,t=token){const access=t||await auth();if(!access)return;setError('');const [a,b]=await Promise.all([fetch(`/api/admin/data?section=${sec}`,{headers:{Authorization:`Bearer ${access}`}}),fetch('/api/admin/summary',{headers:{Authorization:`Bearer ${access}`}})]);if(a.status===403||b.status===403){setError('当前账号没有后台权限');return;}const d=await a.json();const s=await b.json();if(!a.ok){setError(d.error||'加载失败');return;}setRows(d.data||[]);setSummary(s);}
  useEffect(()=>{auth().then(t=>t&&load('members',t));},[]);
  async function action(payload:any){setMsg('处理中…');const r=await fetch('/api/admin/action',{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(payload)});const d=await r.json();setMsg(r.ok?'已保存':d.error||'操作失败');if(r.ok)await load(section);return r.ok;}
  async function switchSection(s:Section){setSection(s);await load(s);}
  return <main className="shell"><header className="top"><div><div className="brand">会员助手 · 管理后台</div><div className="muted">{summary?.adminName||'权限校验中'}</div></div><a href="/">会员端</a></header>
  <nav style={{display:'flex',gap:8,flexWrap:'wrap',margin:'18px 0'}}>{sections.map(([k,n])=><button key={k} className="btn" style={{opacity:section===k?1:.55}} onClick={()=>switchSection(k)}>{n}</button>)}</nav>
  {summary?<section className="grid" style={{marginBottom:18}}><div className="card"><b>会员</b><div className="big">{summary.members}</div></div><div className="card"><b>待处理客服</b><div className="big">{summary.openSupport}</div></div><div className="card"><b>待审反馈</b><div className="big">{summary.pendingFeedback}</div></div><div className="card"><b>待发送</b><div className="big">{summary.undelivered}</div></div></section>:null}
  {error?<div className="card">{error}</div>:<SectionView section={section} rows={rows} action={action}/>}<div className="status">{msg}</div></main>;
}

function SectionView({section,rows,action}:{section:Section;rows:any[];action:(p:any)=>Promise<boolean>}){
 if(section==='members')return <section>{rows.map(r=><form key={r.id} className="card" style={{marginBottom:10}} onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);action({action:'member.update',id:r.id,status:f.get('status'),level:f.get('level'),expires_at:f.get('expires_at')})}}><b>{r.account_name||r.member_no||r.user_id}</b><div className="muted">{r.member_no||'无会员号'} · {r.user_id}</div><div style={{display:'flex',gap:8,marginTop:10,flexWrap:'wrap'}}><select className="input" name="status" defaultValue={r.status}><option>active</option><option>inactive</option><option>suspended</option><option>expired</option></select><input className="input" name="level" type="number" min="0" defaultValue={r.level}/><input className="input" name="expires_at" type="datetime-local" defaultValue={r.expires_at?.slice(0,16)||''}/><button className="btn">保存</button></div></form>)}</section>;
 if(section==='benefits')return <section><BenefitForm action={action}/>{rows.map(r=><div className="card" key={r.id} style={{marginBottom:10}}><b>{r.title}</b><div className="muted">{r.code} · 等级 ≥ {r.min_member_level} · {r.is_enabled?'启用':'停用'}</div><p>{r.description}</p></div>)}</section>;
 if(section==='feedback')return <section>{rows.map(r=><form key={r.id} className="card" style={{marginBottom:10}} onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);action({action:'feedback.update',id:r.id,status:f.get('status'),priority:f.get('priority'),admin_note:f.get('admin_note')})}}><b>{r.title||r.desired_feature}</b><p>{r.current_problem}</p><div className="muted">场景：{r.use_case||'—'} ｜ 目标：{r.desired_outcome||'—'}</div><div style={{display:'flex',gap:8,marginTop:10,flexWrap:'wrap'}}><select className="input" name="status" defaultValue={r.status}>{['submitted','reviewing','planned','in_progress','completed','rejected','closed'].map(x=><option key={x}>{x}</option>)}</select><select className="input" name="priority" defaultValue={r.priority}>{['low','normal','high','urgent'].map(x=><option key={x}>{x}</option>)}</select><input className="input" name="admin_note" defaultValue={r.admin_note||''} placeholder="后台处理备注"/><button className="btn">更新</button></div></form>)}</section>;
 if(section==='support')return <section>{rows.map(r=><div className="card" key={r.id} style={{marginBottom:10}}><b>{r.subject||'会员咨询'}</b><div className="muted">{r.status} · {r.priority}</div><div style={{margin:'10px 0'}}>{(r.messages||[]).map((m:any)=><div key={m.id}><b>{m.sender_role}：</b>{m.body}</div>)}</div><form onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);action({action:'support.reply',conversation_id:r.id,message:f.get('message'),status:'pending'});e.currentTarget.reset()}}><div style={{display:'flex',gap:8}}><input className="input" name="message" placeholder="回复会员" required/><button className="btn">发送回复</button><button type="button" className="btn" onClick={()=>action({action:'support.status',id:r.id,status:'closed'})}>关闭</button></div></form></div>)}</section>;
 if(section==='navigation')return <section><NavigationForm action={action}/>{rows.map(r=><div className="card" key={r.id} style={{marginBottom:10}}><b>{r.title}</b><div className="muted">{r.category||'未分类'} · 等级 ≥ {r.min_member_level} · {r.is_enabled?'启用':'停用'}</div><div>{r.url}</div></div>)}</section>;
 return <section><NotificationForm action={action}/>{rows.map(r=><div className="card" key={r.id} style={{marginBottom:10}}><b>{r.title}</b><div className="muted">{r.status} · {r.kind} · {new Date(r.created_at).toLocaleString()}</div><p>{r.body}</p></div>)}</section>;
}

function BenefitForm({action}:{action:(p:any)=>Promise<boolean>}){return <form className="card form" style={{marginBottom:14}} onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);action({action:'benefit.upsert',code:f.get('code'),title:f.get('title'),description:f.get('description'),benefit_type:f.get('benefit_type'),min_member_level:f.get('min_member_level'),sort_order:f.get('sort_order')}).then(ok=>ok&&e.currentTarget.reset())}}><h2>新增权益</h2><input className="input" name="code" placeholder="唯一代码" required/><input className="input" name="title" placeholder="权益名称" required/><input className="input" name="description" placeholder="说明"/><input className="input" name="benefit_type" placeholder="类型" defaultValue="general"/><input className="input" name="min_member_level" type="number" min="0" defaultValue="0"/><input className="input" name="sort_order" type="number" defaultValue="0"/><button className="btn">新增</button></form>}
function NavigationForm({action}:{action:(p:any)=>Promise<boolean>}){return <form className="card form" style={{marginBottom:14}} onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);action({action:'navigation.upsert',title:f.get('title'),url:f.get('url'),description:f.get('description'),category:f.get('category'),min_member_level:f.get('min_member_level'),sort_order:f.get('sort_order')}).then(ok=>ok&&e.currentTarget.reset())}}><h2>新增平台导航</h2><input className="input" name="title" placeholder="网站名称" required/><input className="input" name="url" type="url" placeholder="https://" required/><input className="input" name="description" placeholder="说明"/><input className="input" name="category" placeholder="分类"/><input className="input" name="min_member_level" type="number" min="0" defaultValue="0"/><input className="input" name="sort_order" type="number" defaultValue="0"/><button className="btn">新增</button></form>}
function NotificationForm({action}:{action:(p:any)=>Promise<boolean>}){return <form className="card form" style={{marginBottom:14}} onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);action({action:'notification.broadcast',kind:f.get('kind'),title:f.get('title'),message:f.get('message'),action_url:f.get('action_url'),min_level:f.get('min_level'),scheduled_at:f.get('scheduled_at')||null}).then(ok=>ok&&e.currentTarget.reset())}}><h2>创建群发通知</h2><input className="input" name="kind" defaultValue="general" placeholder="通知类型"/><input className="input" name="title" placeholder="标题" required/><textarea className="input" name="message" rows={3} placeholder="通知内容" required/><input className="input" name="action_url" type="url" placeholder="可选跳转链接"/><input className="input" name="min_level" type="number" min="0" defaultValue="0"/><input className="input" name="scheduled_at" type="datetime-local"/><button className="btn">创建并进入发送队列</button></form>}
