'use client';

import { useEffect, useState } from 'react';
import { createBrowserSupabase } from '@/lib/supabase/client';

type Benefit={id:string,status:string,quota:number|null,used_count:number,benefit:{title:string;description:string|null}[]};
type Nav={id:string;title:string;url:string;description:string|null};
type Note={id:string;title:string;body:string;read_at:string|null;created_at:string};

export default function MemberHome(){
 const [loading,setLoading]=useState(true);const [userId,setUserId]=useState('');const [name,setName]=useState('会员');const [memberNo,setMemberNo]=useState('');const [benefits,setBenefits]=useState<Benefit[]>([]);const [links,setLinks]=useState<Nav[]>([]);const [notes,setNotes]=useState<Note[]>([]);const [bindCode,setBindCode]=useState('');const [bindMsg,setBindMsg]=useState('');
 useEffect(()=>{(async()=>{const s=createBrowserSupabase();const {data:{user}}=await s.auth.getUser();if(!user){setLoading(false);return;}setUserId(user.id);const {data:m}=await s.from('membership_accounts').select('account_name,member_no').eq('user_id',user.id).maybeSingle();setName(m?.account_name||'会员');setMemberNo(m?.member_no||'');const [{data:b},{data:l},{data:n}]=await Promise.all([s.from('member_benefit_assignments').select('id,status,quota,used_count,benefit:member_benefits(title,description)').eq('user_id',user.id).order('created_at',{ascending:false}),s.from('navigation_links').select('id,title,url,description').order('sort_order'),s.from('member_notification_messages').select('id,title,body,read_at,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(8)]);setBenefits((b||[]) as unknown as Benefit[]);setLinks((l||[]) as Nav[]);setNotes((n||[]) as Note[]);setLoading(false);})();},[]);
 async function createBindCode(){setBindMsg('生成中…');const s=createBrowserSupabase();const {data:{session}}=await s.auth.getSession();if(!session)return;const r=await fetch('/api/telegram/bind-code',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`}});const d=await r.json();if(!r.ok){setBindMsg(d.error||'生成失败');return;}setBindCode(d.code);setBindMsg(`10 分钟内到 Telegram Bot 发送 /bind ${d.code}`);}
 if(loading)return <main className="shell">加载中…</main>;
 if(!userId)return <main className="shell"><header className="top"><div><div className="brand">会员权益助手</div><div className="muted">查询不要求登录</div></div><a href="/login">登录</a></header><section className="grid"><div className="card wide"><h2>先查再说</h2><p>不登录也可以按站点、金额、分类查询可参与权益。本次只记录匿名查询，不保存会员账户资料。</p><a className="btn" href="/query">开始查询</a></div><div className="card wide"><h2>登录后有什么不同？</h2><div className="muted">登录后保存会员账户、等级、常用查询条件和历史偏好，并提供个人权益、提醒、客服记录与 Telegram 绑定。</div></div></section></main>;
 return <main className="shell"><header className="top"><div><div className="brand">会员权益助手</div><div className="muted">你好，{name}{memberNo?` · 编号 ${memberNo}`:''}</div></div><div style={{display:'flex',gap:8}}><a className="btn secondary" href="/query">权益查询</a><a className="btn secondary" href="/feedback">功能许愿</a></div></header><section className="grid"><div className="card"><h2>我的权益</h2><div className="big">{benefits.filter(x=>x.status==='active').length}</div><div className="muted">当前可用</div></div><div className="card"><h2>未读通知</h2><div className="big">{notes.filter(x=>!x.read_at).length}</div><div className="muted">最新消息</div></div><div className="card"><h2>快捷服务</h2><a href="/support">联系客服 →</a></div><div className="card"><h2>Telegram</h2><button className="btn" onClick={createBindCode}>绑定 Telegram</button>{bindCode?<div className="big" style={{fontSize:24,marginTop:10}}>{bindCode}</div>:null}<div className="muted">{bindMsg}</div></div><div className="card wide"><h2>会员福利</h2><div className="list">{benefits.length?benefits.map(x=>{const b=x.benefit?.[0];return <div className="row" key={x.id}><div><strong>{b?.title||'会员权益'}</strong><div className="muted">{b?.description||x.status}</div></div><span>{x.quota==null?'不限':`剩余 ${Math.max(0,x.quota-x.used_count)} 次`}</span></div>}):<div className="muted">暂无已分配权益</div>}</div></div><div className="card wide"><h2>网站导航</h2><div className="list">{links.map(x=><a className="row" href={x.url} target="_blank" rel="noreferrer" key={x.id}><div><strong>{x.title}</strong><div className="muted">{x.description}</div></div><span>打开 →</span></a>)}</div></div><div className="card wide"><h2>最新通知</h2><div className="list">{notes.length?notes.map(x=><div className="row" key={x.id}><div><strong>{x.title}</strong><div className="muted">{x.body}</div></div><span className="status">{x.read_at?'已读':'未读'}</span></div>):<div className="muted">暂无通知</div>}</div></div></section></main>;
}
