'use client';

import { useEffect, useState } from 'react';
import { createBrowserSupabase } from '@/lib/supabase/client';

type Benefit={id:string;status:string;quota:number|null;used_count:number;benefit:{title:string;description:string|null}|null};
type Nav={id:string;title:string;url:string;description:string|null};
type Note={id:string;title:string;body:string;read_at:string|null;created_at:string};

export default function MemberHome(){
 const [loading,setLoading]=useState(true);const [name,setName]=useState('会员');const [benefits,setBenefits]=useState<Benefit[]>([]);const [links,setLinks]=useState<Nav[]>([]);const [notes,setNotes]=useState<Note[]>([]);
 useEffect(()=>{(async()=>{const s=createBrowserSupabase();const {data:{user}}=await s.auth.getUser();if(!user){location.href='/login';return;}const {data:m}=await s.from('membership_accounts').select('account_name,level').eq('user_id',user.id).maybeSingle();setName(m?.account_name||user.email||'会员');const [{data:b},{data:l},{data:n}]=await Promise.all([s.from('member_benefit_assignments').select('id,status,quota,used_count,benefit:member_benefits(title,description)').eq('user_id',user.id).order('created_at',{ascending:false}),s.from('navigation_links').select('id,title,url,description').order('sort_order'),s.from('member_notification_messages').select('id,title,body,read_at,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(8)]);setBenefits((b||[]) as Benefit[]);setLinks((l||[]) as Nav[]);setNotes((n||[]) as Note[]);setLoading(false);})();},[]);
 if(loading)return <main className="shell">加载中…</main>;
 return <main className="shell"><header className="top"><div><div className="brand">会员权益助手</div><div className="muted">你好，{name}</div></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><a className="btn secondary" href="/telegram-bind">绑定 Telegram</a><a className="btn secondary" href="/feedback">功能许愿</a></div></header><section className="grid"><div className="card"><h2>我的权益</h2><div className="big">{benefits.filter(x=>x.status==='active').length}</div><div className="muted">当前可用</div></div><div className="card"><h2>未读通知</h2><div className="big">{notes.filter(x=>!x.read_at).length}</div><div className="muted">最新消息</div></div><div className="card"><h2>快捷服务</h2><a href="/support">联系客服 →</a></div><div className="card wide"><h2>会员福利</h2><div className="list">{benefits.length?benefits.map(x=>{const left=x.quota==null?'不限':`剩余 ${Math.max(0,(x.quota||0)-(x.used_count||0))} 次`;return <div className="row" key={x.id}><div><strong>{x.benefit?.title||'会员权益'}</strong><div className="muted">{x.benefit?.description||x.status}</div></div><span>{left}</span></div>}):<div className="muted">暂无已分配权益</div>}</div></div><div className="card wide"><h2>网站导航</h2><div className="list">{links.map(x=><a className="row" href={x.url} target="_blank" rel="noreferrer" key={x.id}><div><strong>{x.title}</strong><div className="muted">{x.description}</div></div><span>打开 →</span></a>)}</div></div><div className="card wide"><h2>最新通知</h2><div className="list">{notes.length?notes.map(x=><div className="row" key={x.id}><div><strong>{x.title}</strong><div className="muted">{x.body}</div></div><span className="status">{x.read_at?'已读':'未读'}</span></div>):<div className="muted">暂无通知</div>}</div></div></section></main>;
}
